name: 同步Sync Code to Gitee

on:
  workflow_dispatch:    # 仅手动触发

jobs:
  sync-code-to-gitee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: adambirds/sync-github-to-gitlab-action@v1.1.0
        with:
          destination_repository: git@gitee.com:hashgopeed/agent.git
          destination_branch_name: master
          destination_ssh_key: ${{ secrets.GITEE_SSH_KEY }}
