name: 测试Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:  # 允许手动触发

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sync-release:
    runs-on: ubuntu-latest
    needs: goreleaser
    if: success()
    steps:
      - name: Trigger external sync
        run: |
          echo "Release completed, ready for external sync"
