name: 测试Release

on:
  push:
    tags:
      - "v*"
    branches:
      - main
    paths-ignore:
      - ".github/workflows/agent.yml"
      - ".github/workflows/codeql-analysis.yml"
      - ".github/workflows/test.yml"
      - ".github/workflows/contributors.yml"
      - "README.md"
      - ".goreleaser.yml"
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 手动触发支持

jobs:
  # 测试构建（用于 PR 和分支推送）
  test-build:
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.25.2

      - name: Run GoReleaser snapshot
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: build --clean --snapshot

  # 正式发布（仅用于标签推送）
  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 必需，用于创建 releases
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GHCR_PAT }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.25.2

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          # 使用您的 GHCR_PAT 作为 GitHub Token
          GITHUB_TOKEN: ${{ secrets.GHCR_PAT }}

      - name: Verify release
        run: |
          echo "Release completed for tag: ${{ github.ref_name }}"
          echo "Check https://github.com/${{ github.repository }}/releases"
